# Generated by Django 5.0.2 on 2024-02-29 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HeadAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.director')),
            ],
        ),
        migrations.CreateModel(
            name='MainIngenire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.headassistant')),
            ],
        ),
        migrations.CreateModel(
            name='Ingenire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.master')),
            ],
        ),
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.ingenire')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.mainingenire')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='boss_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.seniormaster'),
        ),
    ]
