# Generated by Django 5.0.2 on 2024-03-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250)),
                ('job_position', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workerstree.position')),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker', models.CharField(max_length=250)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerstree.workers')),
            ],
        ),
    ]
